import type { PageDefinition } from "../types.ts";
import { definePage } from "./common.ts";

export const projectPageDefinitions = [
  definePage({
    id: "project-category-cross",
    feature: "project",
    source: "ltf-front/app/pages/project/[category1]/[category2]/index.vue",
    pattern: ["project", ":category1", ":category2"],
    title: "カテゴリ別案件一覧",
    description: "指定したカテゴリ条件に合うフリーランス案件を一覧で確認できます。",
    eyebrow: "案件検索",
  }),
  definePage({
    id: "project-category-cross-ppage",
    feature: "project",
    source: "ltf-front/app/pages/project/[category1]/[category2]/p[page]/index.vue",
    pattern: ["project", ":category1", ":category2", "p:page"],
    title: "カテゴリ別案件一覧",
    description: "指定したカテゴリ条件に合うフリーランス案件をページ別に確認できます。",
    eyebrow: "案件検索",
  }),
  definePage({
    id: "project-category",
    feature: "project",
    source: "ltf-front/app/pages/project/[category1]/index.vue",
    pattern: ["project", ":category1"],
    title: "カテゴリ別案件一覧",
    description: "指定したカテゴリのフリーランス案件を一覧で確認できます。",
    eyebrow: "案件検索",
  }),
  definePage({
    id: "project-category-ppage",
    feature: "project",
    source: "ltf-front/app/pages/project/[category1]/p[page]/index.vue",
    pattern: ["project", ":category1", "p:page"],
    title: "カテゴリ別案件一覧",
    description: "指定したカテゴリのフリーランス案件をページ別に確認できます。",
    eyebrow: "案件検索",
  }),
  definePage({
    id: "project-closedsearch",
    feature: "project",
    source: "ltf-front/app/pages/project/closedsearch/index.vue",
    pattern: ["project", "closedsearch"],
    title: "募集終了案件検索",
    description: "募集終了した案件を検索し、市場傾向や過去の募集内容を確認できます。",
    eyebrow: "案件検索",
  }),
  definePage({
    id: "project-closedsearch-ppage",
    feature: "project",
    source: "ltf-front/app/pages/project/closedsearch/p[page]/index.vue",
    pattern: ["project", "closedsearch", "p:page"],
    title: "募集終了案件検索",
    description: "募集終了した案件をページ別に確認できます。",
    eyebrow: "案件検索",
  }),
  definePage({
    id: "project-detail-id",
    feature: "project",
    source: "ltf-front/app/pages/project/detail/[id]/index.vue",
    pattern: ["project", "detail", ":id"],
    title: "案件詳細",
    description: "案件の業務内容、単価、契約条件、必要スキルを確認できます。",
    eyebrow: "案件詳細",
  }),
  definePage({
    id: "project-marketprice",
    feature: "project",
    source: "ltf-front/app/pages/project/marketprice/index.vue",
    pattern: ["project", "marketprice"],
    title: "単価相場",
    description: "スキルや職種ごとの案件単価相場を確認できます。",
    eyebrow: "単価相場",
  }),
  definePage({
    id: "project-search",
    feature: "project",
    source: "ltf-front/app/pages/project/search/index.vue",
    pattern: ["project", "search"],
    title: "フリーランス案件検索",
    description: "条件を指定してフリーランスエンジニア向け案件を検索できます。",
    eyebrow: "案件検索",
  }),
  definePage({
    id: "project-search-ppage",
    feature: "project",
    source: "ltf-front/app/pages/project/search/p[page]/index.vue",
    pattern: ["project", "search", "p:page"],
    title: "フリーランス案件検索",
    description: "条件に合うフリーランスエンジニア向け案件をページ別に確認できます。",
    eyebrow: "案件検索",
  }),
  definePage({
    id: "project-undecided",
    feature: "project",
    source: "ltf-front/app/pages/project/undecided/index.vue",
    pattern: ["project", "undecided"],
    title: "検討中案件",
    description: "検討中の案件を確認し、応募や相談に進めます。",
    eyebrow: "案件検索",
  }),
] as const satisfies readonly PageDefinition[];
