import type { PageDefinition } from "../types.ts";
import { definePage } from "./common.ts";

export const servicePageDefinitions = [
  definePage({
    id: "service-assess-complete",
    feature: "service",
    source: "ltf-front/app/pages/service/assess/complete/index.vue",
    pattern: ["service", "assess", "complete"],
    title: "単価診断結果",
    description: "入力内容に基づく単価診断結果を確認できます。",
    eyebrow: "診断",
  }),
  definePage({
    id: "service-assess",
    feature: "service",
    source: "ltf-front/app/pages/service/assess/index.vue",
    pattern: ["service", "assess"],
    title: "フリーランス単価診断",
    description: "スキルや経験をもとにフリーランス案件の単価目安を診断できます。",
    eyebrow: "診断",
  }),
  definePage({
    id: "service-first-freelance",
    feature: "service",
    source: "ltf-front/app/pages/service/first-freelance/index.vue",
    pattern: ["service", "first-freelance"],
    title: "はじめてのフリーランス",
    description: "初めてフリーランスを検討する方向けに、準備や支援内容を紹介します。",
    eyebrow: "サービス",
  }),
  definePage({
    id: "service",
    feature: "service",
    source: "ltf-front/app/pages/service/index.vue",
    pattern: ["service"],
    title: "サービス紹介",
    description: "レバテックフリーランスのサービス内容とサポート体制を紹介します。",
    eyebrow: "サービス",
  }),
  definePage({
    id: "service-merit-accountant-1",
    feature: "service",
    source: "ltf-front/app/pages/service/merit/accountant/1/index.vue",
    pattern: ["service", "merit", "accountant", "1"],
    title: "税理士紹介サービス",
    description: "フリーランス向けの税理士紹介サービスを紹介します。",
    eyebrow: "サービス",
  }),
  definePage({
    id: "service-onsite",
    feature: "service",
    source: "ltf-front/app/pages/service/onsite/index.vue",
    pattern: ["service", "onsite"],
    title: "常駐案件サポート",
    description: "常駐型案件の特徴とサポート内容を紹介します。",
    eyebrow: "サービス",
  }),
  definePage({
    id: "service-phone",
    feature: "service",
    source: "ltf-front/app/pages/service/phone/index.vue",
    pattern: ["service", "phone"],
    title: "電話相談",
    description: "フリーランス案件やキャリアについて電話で相談できます。",
    eyebrow: "サービス",
  }),
  definePage({
    id: "service-pickup",
    feature: "service",
    source: "ltf-front/app/pages/service/pickup/index.vue",
    pattern: ["service", "pickup"],
    title: "注目サービス",
    description: "レバテックフリーランスの注目サービスを紹介します。",
    eyebrow: "サービス",
  }),
  definePage({
    id: "service-platform",
    feature: "service",
    source: "ltf-front/app/pages/service/platform/index.vue",
    pattern: ["service", "platform"],
    title: "プラットフォームサービス",
    description: "フリーランス向けプラットフォームサービスを紹介します。",
    eyebrow: "サービス",
  }),
  definePage({
    id: "service-platform-member",
    feature: "service",
    source: "ltf-front/app/pages/service/platform/member/index.vue",
    pattern: ["service", "platform", "member"],
    title: "会員向けプラットフォーム",
    description: "会員向けのプラットフォーム機能と利用メリットを紹介します。",
    eyebrow: "サービス",
  }),
] as const satisfies readonly PageDefinition[];
